name: fruits_ecommerce
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  dots_indicator: ^4.0.1
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8
  firebase_core: ^3.14.0
  dartz: ^0.10.1
  firebase_auth: ^5.6.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.2.0
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.1.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  modal_progress_hud_nsn: ^0.5.1
  logger: ^2.6.0
  cloud_firestore: ^5.6.10
  skeletonizer: ^2.1.0+1
  cached_network_image: ^3.4.1
  provider: ^6.1.5+1
  flutter_paypal_payment: ^1.0.8
  uuid: ^4.5.2
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  intl_utils: ^2.8.3

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
   - family: Cairo
     fonts:
       - asset: assets/fonts/cairo/Cairo-Black.ttf
         weight: 900
       - asset: assets/fonts/cairo/Cairo-Bold.ttf
         weight: 700
       - asset: assets/fonts/cairo/Cairo-ExtraBold.ttf
         weight: 800
       - asset: assets/fonts/cairo/Cairo-ExtraLight.ttf
         weight: 200
       - asset: assets/fonts/cairo/Cairo-Light.ttf
         weight: 300
       - asset: assets/fonts/cairo/Cairo-Medium.ttf
         weight: 500
       - asset: assets/fonts/cairo/Cairo-Regular.ttf
         weight: 400
       - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
         weight: 600

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
flutter_intl:
  enabled: true